package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

const generatedHeader = "# Generated by external-dns-dnsmasq-webhook. Do not edit.\n"

type commandRunner func(context.Context, string, ...string) error

type provider struct {
	mu            sync.Mutex
	domain        string
	stateFile     string
	configFile    string
	dnsmasqBinary string
	systemctl     string
	service       string
	records       map[string]*endpoint
	run           commandRunner
}

func newProvider(cfg config) (*provider, error) {
	p := &provider{
		domain:        cfg.Domain,
		stateFile:     cfg.StateFile,
		configFile:    cfg.DNSMasqConfigFile,
		dnsmasqBinary: cfg.DNSMasqBinary,
		systemctl:     cfg.SystemctlBinary,
		service:       cfg.DNSMasqService,
		records:       make(map[string]*endpoint),
		run:           runCommand,
	}
	if err := p.load(); err != nil {
		return nil, err
	}
	return p, nil
}

func (p *provider) load() error {
	data, err := os.ReadFile(p.stateFile)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read state: %w", err)
	}
	var records []*endpoint
	if err := json.Unmarshal(data, &records); err != nil {
		return fmt.Errorf("decode state: %w", err)
	}
	for _, record := range records {
		normalized, err := p.normalize(record)
		if err != nil {
			return fmt.Errorf("invalid record in state: %w", err)
		}
		p.records[recordKey(normalized)] = normalized
	}
	return nil
}

func (p *provider) reconcile(ctx context.Context) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	data := renderDNSMasqConfig(p.sortedRecords())
	if err := writeAtomic(p.configFile, data, 0o644); err != nil {
		return fmt.Errorf("write dnsmasq configuration: %w", err)
	}
	if err := p.checkAndRestart(ctx); err != nil {
		return err
	}
	return nil
}

func (p *provider) list() []*endpoint {
	p.mu.Lock()
	defer p.mu.Unlock()
	return cloneEndpoints(p.sortedRecords())
}

func (p *provider) adjust(records []*endpoint) []*endpoint {
	adjusted := make([]*endpoint, 0, len(records))
	for _, record := range records {
		normalized, err := p.normalize(record)
		if err != nil {
			slog.Warn("dropping unsupported DNS endpoint", "name", recordName(record), "error", err)
			continue
		}
		adjusted = append(adjusted, normalized)
	}
	return adjusted
}

func (p *provider) apply(ctx context.Context, requested *changes) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	next := cloneRecordMap(p.records)
	for _, record := range append(requested.Delete, requested.UpdateOld...) {
		normalized, err := p.normalize(record)
		if err != nil {
			return fmt.Errorf("invalid record removal: %w", err)
		}
		delete(next, recordKey(normalized))
	}
	for _, record := range append(requested.Create, requested.UpdateNew...) {
		normalized, err := p.normalize(record)
		if err != nil {
			return fmt.Errorf("invalid record addition: %w", err)
		}
		next[recordKey(normalized)] = normalized
	}
	if err := validateRecordSet(next); err != nil {
		return err
	}

	newRecords := sortedRecordMap(next)
	newState, err := json.MarshalIndent(newRecords, "", "  ")
	if err != nil {
		return fmt.Errorf("encode state: %w", err)
	}
	newState = append(newState, '\n')
	newConfig := renderDNSMasqConfig(newRecords)

	oldState, stateExisted, err := readOptional(p.stateFile)
	if err != nil {
		return fmt.Errorf("read previous state: %w", err)
	}
	oldConfig, configExisted, err := readOptional(p.configFile)
	if err != nil {
		return fmt.Errorf("read previous dnsmasq configuration: %w", err)
	}
	if bytes.Equal(oldState, newState) && bytes.Equal(oldConfig, newConfig) {
		p.records = next
		return nil
	}

	if err := writeAtomic(p.configFile, newConfig, 0o644); err != nil {
		return fmt.Errorf("write dnsmasq configuration: %w", err)
	}
	if err := p.runCheck(ctx); err != nil {
		_ = restoreFile(p.configFile, oldConfig, configExisted, 0o644)
		return fmt.Errorf("validate dnsmasq configuration: %w", err)
	}
	if err := writeAtomic(p.stateFile, newState, 0o600); err != nil {
		_ = restoreFile(p.configFile, oldConfig, configExisted, 0o644)
		return fmt.Errorf("write state: %w", err)
	}
	if err := p.runRestart(ctx); err != nil {
		rollbackErr := restoreFile(p.configFile, oldConfig, configExisted, 0o644)
		rollbackErr = errors.Join(rollbackErr, restoreFile(p.stateFile, oldState, stateExisted, 0o600))
		rollbackErr = errors.Join(rollbackErr, p.runRestart(context.Background()))
		return errors.Join(fmt.Errorf("restart dnsmasq: %w", err), rollbackErr)
	}

	p.records = next
	return nil
}

func (p *provider) normalize(record *endpoint) (*endpoint, error) {
	if record == nil {
		return nil, errors.New("record is null")
	}
	result := &endpoint{
		DNSName:    strings.ToLower(strings.TrimSuffix(record.DNSName, ".")),
		RecordType: strings.ToUpper(record.RecordType),
		RecordTTL:  record.RecordTTL,
	}
	if err := validateDNSName(result.DNSName, true); err != nil {
		return nil, err
	}
	matchName := strings.TrimPrefix(result.DNSName, "*.")
	if matchName != p.domain && !strings.HasSuffix(matchName, "."+p.domain) {
		return nil, fmt.Errorf("%q is outside managed domain %q", result.DNSName, p.domain)
	}
	if record.SetIdentifier != "" {
		return nil, errors.New("setIdentifier is not supported")
	}
	if len(record.ProviderSpecific) != 0 {
		return nil, errors.New("providerSpecific properties are not supported")
	}
	if result.RecordTTL < 0 {
		return nil, errors.New("recordTTL cannot be negative")
	}
	if len(record.Targets) == 0 {
		return nil, errors.New("record must contain at least one target")
	}

	seen := make(map[string]struct{}, len(record.Targets))
	for _, target := range record.Targets {
		target = strings.ToLower(strings.TrimSuffix(target, "."))
		switch result.RecordType {
		case "A":
			address, err := netip.ParseAddr(target)
			if err != nil || !address.Is4() {
				return nil, fmt.Errorf("target %q is not an IPv4 address for an A record", target)
			}
			target = address.String()
		case "AAAA":
			address, err := netip.ParseAddr(target)
			if err != nil || !address.Is6() || address.Is4In6() {
				return nil, fmt.Errorf("AAAA target %q is not an IPv6 address", target)
			}
			target = address.String()
		case "CNAME":
			if strings.HasPrefix(result.DNSName, "*.") {
				return nil, errors.New("wildcard CNAME records are not supported")
			}
			if err := validateDNSName(target, false); err != nil {
				return nil, fmt.Errorf("invalid CNAME target: %w", err)
			}
			if target == result.DNSName {
				return nil, errors.New("CNAME target cannot refer to itself")
			}
		default:
			return nil, fmt.Errorf("record type %q is not supported", result.RecordType)
		}
		seen[target] = struct{}{}
	}
	if result.RecordType == "CNAME" && len(seen) != 1 {
		return nil, errors.New("CNAME records must contain exactly one target")
	}
	for target := range seen {
		result.Targets = append(result.Targets, target)
	}
	sort.Strings(result.Targets)
	return result, nil
}

func (p *provider) sortedRecords() []*endpoint {
	return sortedRecordMap(p.records)
}

func (p *provider) checkAndRestart(ctx context.Context) error {
	if err := p.runCheck(ctx); err != nil {
		return fmt.Errorf("validate dnsmasq configuration: %w", err)
	}
	if err := p.runRestart(ctx); err != nil {
		return fmt.Errorf("restart dnsmasq: %w", err)
	}
	return nil
}

func (p *provider) runCheck(ctx context.Context) error {
	return p.run(ctx, p.dnsmasqBinary, "--test")
}

func (p *provider) runRestart(ctx context.Context) error {
	return p.run(ctx, p.systemctl, "restart", p.service)
}

func runCommand(parent context.Context, name string, args ...string) error {
	ctx, cancel := context.WithTimeout(parent, 20*time.Second)
	defer cancel()
	output, err := exec.CommandContext(ctx, name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %w: %s", name, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func renderDNSMasqConfig(records []*endpoint) []byte {
	var output strings.Builder
	output.WriteString(generatedHeader)
	for _, record := range records {
		if strings.HasPrefix(record.DNSName, "*.") {
			domain := strings.TrimPrefix(record.DNSName, "*.")
			for _, target := range record.Targets {
				fmt.Fprintf(&output, "address=/%s/%s\n", domain, target)
			}
			continue
		}
		switch record.RecordType {
		case "A", "AAAA":
			for _, target := range record.Targets {
				fmt.Fprintf(&output, "host-record=%s,%s\n", record.DNSName, target)
			}
		case "CNAME":
			fmt.Fprintf(&output, "cname=%s,%s\n", record.DNSName, record.Targets[0])
		}
	}
	return []byte(output.String())
}

func validateDNSName(name string, allowWildcard bool) error {
	if allowWildcard && strings.HasPrefix(name, "*.") {
		name = strings.TrimPrefix(name, "*.")
	}
	if name == "" || len(name) > 253 {
		return fmt.Errorf("invalid DNS name %q", name)
	}
	for _, label := range strings.Split(name, ".") {
		if len(label) == 0 || len(label) > 63 {
			return fmt.Errorf("invalid DNS label %q", label)
		}
		for i, character := range label {
			valid := character >= 'a' && character <= 'z' || character >= '0' && character <= '9' || character == '-'
			if !valid || character == '-' && (i == 0 || i == len(label)-1) {
				return fmt.Errorf("invalid DNS label %q", label)
			}
		}
	}
	return nil
}

func recordKey(record *endpoint) string {
	return record.DNSName + "\x00" + record.RecordType
}

func recordName(record *endpoint) string {
	if record == nil {
		return ""
	}
	return record.DNSName
}

func validateRecordSet(records map[string]*endpoint) error {
	typesByName := make(map[string]map[string]struct{})
	for _, record := range records {
		if typesByName[record.DNSName] == nil {
			typesByName[record.DNSName] = make(map[string]struct{})
		}
		typesByName[record.DNSName][record.RecordType] = struct{}{}
	}
	for name, types := range typesByName {
		if _, hasCNAME := types["CNAME"]; hasCNAME && len(types) != 1 {
			return fmt.Errorf("CNAME %q conflicts with another record type", name)
		}
	}
	return nil
}

func sortedRecordMap(records map[string]*endpoint) []*endpoint {
	result := make([]*endpoint, 0, len(records))
	for _, record := range records {
		result = append(result, record)
	}
	sort.Slice(result, func(i, j int) bool {
		return recordKey(result[i]) < recordKey(result[j])
	})
	return result
}

func cloneRecordMap(records map[string]*endpoint) map[string]*endpoint {
	result := make(map[string]*endpoint, len(records))
	for key, record := range records {
		result[key] = cloneEndpoint(record)
	}
	return result
}

func cloneEndpoints(records []*endpoint) []*endpoint {
	result := make([]*endpoint, 0, len(records))
	for _, record := range records {
		result = append(result, cloneEndpoint(record))
	}
	return result
}

func cloneEndpoint(record *endpoint) *endpoint {
	result := *record
	result.Targets = append([]string(nil), record.Targets...)
	return &result
}

func readOptional(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	return data, err == nil, err
}

func restoreFile(path string, data []byte, existed bool, mode os.FileMode) error {
	if !existed {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	return writeAtomic(path, data, mode)
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o750); err != nil {
		return err
	}
	file, err := os.CreateTemp(directory, "."+filepath.Base(path)+".*")
	if err != nil {
		return err
	}
	temporaryName := file.Name()
	defer func() { _ = os.Remove(temporaryName) }()
	if err := file.Chmod(mode); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryName, path)
}
