#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ "${1:-1}" -gt 1 ]; then
		systemctl --system try-restart external-dns-dnsmasq-webhook.service >/dev/null || true
	else
		systemctl --system enable --now external-dns-dnsmasq-webhook.service >/dev/null || true
	fi
fi

exit 0
