#!/bin/sh
set -eu

if [ ! -d /var/lib/external-dns-dnsmasq-webhook ]; then
	mkdir -m 0750 /var/lib/external-dns-dnsmasq-webhook
fi
if [ ! -e /var/lib/external-dns-dnsmasq-webhook/records.conf ]; then
	umask 022
	: >/var/lib/external-dns-dnsmasq-webhook/records.conf
fi

exit 0
