#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = purge ]; then
	deb-systemd-helper purge external-dns-dnsmasq-webhook.service >/dev/null || true
	deb-systemd-helper unmask external-dns-dnsmasq-webhook.service >/dev/null || true
fi

exit 0
